version: "3"

services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=backend-project
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: backend-app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
